/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartdcs_bms;

import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author PC
 */
public class alarmas_incendios extends javax.swing.JPanel{

    /**
     * Creates new form alarmas_incendios
     */
   
    String date;
    public alarmas_incendios() {
        initComponents();
        
      
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_alarmas = new javax.swing.JTable();
        calendario = new org.jdesktop.swingx.JXMonthView();
        ack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ack_all = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fecha_fin = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        fecha_inicio = new org.jdesktop.swingx.JXDatePicker();
        imprimir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("ALARMAS");

        tabla_alarmas.setAutoCreateRowSorter(true);
        tabla_alarmas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabla_alarmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "HORA", "ALARMA", "ÁREA", "ESTADO", "RESPONSABLE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_alarmas);

        calendario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        calendario.setDaysOfTheWeek(new String[] {"Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"});
        calendario.setDaysOfTheWeekForeground(new java.awt.Color(0, 0, 0));
        calendario.setFirstDayOfWeek(1);
        calendario.setFlaggedDayForeground(java.awt.Color.white);
        calendario.setFont(new java.awt.Font("BankGothic Md BT", 1, 12)); // NOI18N
        calendario.setMonthStringBackground(new java.awt.Color(153, 0, 0));
        calendario.setMonthStringForeground(java.awt.Color.white);
        calendario.setSelectionBackground(new java.awt.Color(255, 204, 0));
        calendario.setTodayBackground(new java.awt.Color(255, 204, 0));
        calendario.setTraversable(true);
        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
        });

        ack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/check.png"))); // NOI18N
        ack.setText("ACK");

        jLabel2.setText("Reconocer selección");

        ack_all.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/doble check.png"))); // NOI18N
        ack_all.setText("ACK ");

        jLabel3.setText("Reconocer todas");

        jLabel4.setFont(new java.awt.Font("BankGothic Md BT", 0, 14)); // NOI18N
        jLabel4.setText("Generar Reporte");

        jLabel5.setFont(new java.awt.Font("BankGothic Md BT", 0, 12)); // NOI18N
        jLabel5.setText("Desde");

        jLabel6.setFont(new java.awt.Font("BankGothic Md BT", 0, 12)); // NOI18N
        jLabel6.setText("Hasta");

        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir 30x30.png"))); // NOI18N
        imprimir.setText("Print");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imprimir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ack)
                                    .addComponent(ack_all))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ack)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ack_all)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(fecha_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imprimir)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked
        // TODO add your handling code here:
        
        try{
           
          
            String fecha=Integer.toString(calendario.getSelectionDate().getDate());
            String mes=Integer.toString(calendario.getSelectionDate().getMonth()+1);
            String año=Integer.toString(calendario.getSelectionDate().getYear()+1900);
        
        date=fecha+"/"+mes+"/"+año;
        
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_calendarioMouseClicked

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ack;
    private javax.swing.JButton ack_all;
    private org.jdesktop.swingx.JXMonthView calendario;
    private org.jdesktop.swingx.JXDatePicker fecha_fin;
    private org.jdesktop.swingx.JXDatePicker fecha_inicio;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_alarmas;
    // End of variables declaration//GEN-END:variables

  
}
