/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartdcs_bms;

import java.io.File;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author PC
 */
public class Inicio extends javax.swing.JFrame {

   
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
     
        Icon icono=new javax.swing.ImageIcon(getClass().getResource("/iconos/edificio_icon1.png"));
                 pestañas.setIconAt(0, icono);
                  pestañas.setIconAt(1, icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_emergente = new javax.swing.JPopupMenu();
        cerrar_pestaña = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        renombrar = new javax.swing.JMenuItem();
        pestañas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        cargar_plano = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        menu_emergente.setBackground(new java.awt.Color(0, 51, 51));

        cerrar_pestaña.setText("Cerrar Pestaña");
        cerrar_pestaña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_pestañaMouseClicked(evt);
            }
        });
        cerrar_pestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar_pestañaActionPerformed(evt);
            }
        });
        menu_emergente.add(cerrar_pestaña);
        menu_emergente.add(jSeparator1);

        renombrar.setText("Cambiar Nombre");
        renombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renombrarActionPerformed(evt);
            }
        });
        menu_emergente.add(renombrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Contra Incendios");
        setBackground(new java.awt.Color(51, 51, 51));

        pestañas.setBackground(new java.awt.Color(51, 51, 51));
        pestañas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pestañas.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        pestañas.setFont(new java.awt.Font("BankGothic Md BT", 1, 14)); // NOI18N
        pestañas.setName(""); // NOI18N
        pestañas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pestañasMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pestañas.addTab("Planta 1", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pestañas.addTab("Planta 2", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pestañas.addTab("+", jPanel2);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName(""); // NOI18N

        cargar_plano.setBackground(new java.awt.Color(204, 204, 204));
        cargar_plano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/upload color 30x30.png"))); // NOI18N
        cargar_plano.setToolTipText("Cargar plano");
        cargar_plano.setFocusable(false);
        cargar_plano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cargar_plano.setName("Cargar plano"); // NOI18N
        cargar_plano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cargar_plano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cargar_planoMouseEntered(evt);
            }
        });
        cargar_plano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_planoActionPerformed(evt);
            }
        });
        jToolBar1.add(cargar_plano);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/valve 30x30.png"))); // NOI18N
        jButton2.setToolTipText("Válvula");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("Válvula"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jToolBar1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pestañas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pestañas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pestañasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pestañasMouseClicked
        // TODO add your handling code here:
         String pestaña=pestañas.getTitleAt(pestañas.getSelectedIndex());
        switch(evt.getButton()){
            /** captura del click izquierdo **/
            case 1:
       
        int num_pestañas=pestañas.getTabCount();
        JPanel planta=new JPanel();
        switch(pestaña){
            case "+":
                
                pestañas.add(planta,num_pestañas-1);
                pestañas.setTitleAt(num_pestañas-1,"Planta "+Integer.toString(num_pestañas));
                  Icon icono=new javax.swing.ImageIcon(getClass().getResource("/iconos/edificio_icon1.png"));
                 pestañas.setIconAt(num_pestañas-1, icono);
              
                break;
        }
        
        break;
        /** captura del click derecho**/
            case 3:
                
          
        if(!pestaña.equals("+")){
           
           menu_emergente.show(this,evt.getX(),evt.getY());
           
           
        }
                
              
            break;
        
    }
    }//GEN-LAST:event_pestañasMouseClicked

    private void cerrar_pestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar_pestañaActionPerformed
        // TODO add your handling code here:
        pestañas.remove(pestañas.getSelectedIndex());
    }//GEN-LAST:event_cerrar_pestañaActionPerformed

    private void cerrar_pestañaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_pestañaMouseClicked
  
   
    }//GEN-LAST:event_cerrar_pestañaMouseClicked

    private void renombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renombrarActionPerformed
        // TODO add your handling code here:
      
JFrame frame = new JFrame("Input dialog");
    String nombre = JOptionPane.showInputDialog(
        frame, 
        "Nuevo nombre", 
        "¿Desea cambiar el nombre?", 
        JOptionPane.WARNING_MESSAGE);
        
       if(nombre!=null){
         pestañas.setTitleAt(pestañas.getSelectedIndex(), nombre);
       }
    }//GEN-LAST:event_renombrarActionPerformed

    private void cargar_planoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargar_planoMouseEntered
      
    
      
    }//GEN-LAST:event_cargar_planoMouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
    
    }//GEN-LAST:event_jButton2MouseEntered

    private void cargar_planoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_planoActionPerformed
 
        //** identifica la pestaña seleccionada**//
        int indexTab=pestañas.getSelectedIndex();
        String tab=pestañas.getTitleAt(indexTab);
        Icon icono=pestañas.getIconAt(indexTab);
  //** abrir imagen de fondo**//
  
   JFileChooser abrir_imagen=new JFileChooser();
   abrir_imagen.setFileFilter(new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif"));
   abrir_imagen.showDialog(this, "Abrir");
   File file = abrir_imagen.getSelectedFile();
   if(file!=null)
   {
  String ruta=file.getPath();
   Icon fondo=new javax.swing.ImageIcon(ruta);
 
 //** crea un Image panel**//
 rojerusan.RSPanelImage imagenpane = new rojerusan.RSPanelImage(); 
  imagenpane.setImagen(fondo);
  
  //** añade el panel a la pestaña seleccionada**//
  pestañas.remove(indexTab);
  pestañas.add(imagenpane, indexTab);
  pestañas.setTitleAt(indexTab, tab);
  pestañas.setIconAt(indexTab, icono);
  pestañas.setSelectedIndex(indexTab);
   }
   else{
       JOptionPane.showMessageDialog(this,"Imagen no válida", 
        "WARNING!", 
        JOptionPane.WARNING_MESSAGE);
   }
    }//GEN-LAST:event_cargar_planoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar_plano;
    private javax.swing.JMenuItem cerrar_pestaña;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPopupMenu menu_emergente;
    public static javax.swing.JTabbedPane pestañas;
    private javax.swing.JMenuItem renombrar;
    // End of variables declaration//GEN-END:variables
}
