/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartdcs_bms;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.dnd.DragSource;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import java.io.File;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import rojerusan.RSPanelImage;

/**
 *
 * @author PC
 */
public class Inicio extends javax.swing.JFrame {

    public Cursor  cur_def  = new Cursor(Cursor.DEFAULT_CURSOR);  //  @jve:decl-index=0:
	public Cursor  cur_move  = DragSource.DefaultMoveDrop;  //  @jve:decl-index=0:
       public rojerusan.RSPanelImage imagenpane;
       RSPanelImage[] paneles=new RSPanelImage[200];
        int indexTab;
        incendios panel_incendios= new incendios();
        alarmas_incendios alarmas = new alarmas_incendios();
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
     this.setLocationRelativeTo(null);
//        Icon icono=new javax.swing.ImageIcon(getClass().getResource("/iconos/edificio_icon1.png"));
//                 pestañas.setIconAt(0, icono);
//                  pestañas.setIconAt(1, icono);
//                  inicializarBarra_herramientas();
sistema();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_menu = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        menu_sistema = new javax.swing.JMenu();
        menu_alarma = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Contra Incendios");
        setBackground(new java.awt.Color(51, 51, 51));

        inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        inicio.setText("Inicio");
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });
        Barra_menu.add(inicio);

        menu_sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edificio_incendio.png"))); // NOI18N
        menu_sistema.setText("Sistema");
        menu_sistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sistemaMouseClicked(evt);
            }
        });
        Barra_menu.add(menu_sistema);

        menu_alarma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/alarma.png"))); // NOI18N
        menu_alarma.setText("Alarmas");
        menu_alarma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_alarmaMouseClicked(evt);
            }
        });
        Barra_menu.add(menu_alarma);

        setJMenuBar(Barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        // TODO add your handling code here:
         
        this.dispose();
        Menu_inicio menu_inicio=new Menu_inicio();
        
        menu_inicio.show();
    }//GEN-LAST:event_inicioMouseClicked

    private void menu_sistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sistemaMouseClicked
      sistema();      
    }//GEN-LAST:event_menu_sistemaMouseClicked

    private void menu_alarmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_alarmaMouseClicked
        // TODO add your handling code here:
        int ancho=super.getWidth();
       int alto=super.getHeight();
       super.remove(panel_incendios);
       
       alarmas.setSize(ancho-30, alto-100);
       super.getContentPane().add(alarmas);
      super.pack();
      super.repaint();
        super.setSize(ancho, alto);
         this.addWindowStateListener(new WindowStateListener(){
          @Override
public void windowStateChanged(WindowEvent e) {
  alarmas.setSize(e.getWindow().getSize().width-30, e.getWindow().getSize().height-100);
    
 }});
    }//GEN-LAST:event_menu_alarmaMouseClicked

   public void sistema(){
       int ancho=super.getWidth();
       int alto=super.getHeight();
       super.remove(alarmas);
       //super.remove(barra_diseño);
       
        panel_incendios.setSize(ancho,alto);
       
      super.getContentPane().add(panel_incendios);
      super.pack();
       super.repaint();
        super.setSize(ancho, alto);
        
        //** ajustar el tamaño del Jpanel al del jframe
      this.addWindowStateListener(new WindowStateListener(){
          @Override
public void windowStateChanged(WindowEvent e) {
  panel_incendios.setSize(e.getWindow().getSize().width-15, e.getWindow().getSize().height-60);
    
 }});
      
   }
    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_menu;
    private javax.swing.JMenu inicio;
    private javax.swing.JMenu menu_alarma;
    private javax.swing.JMenu menu_sistema;
    // End of variables declaration//GEN-END:variables
}
